CREATE DATABASE IF NOT EXISTS aimessage CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'aimessage'@'%' IDENTIFIED BY 'Ren280919@';
GRANT ALL PRIVILEGES ON aimessage.* TO 'aimessage'@'%';
FLUSH PRIVILEGES;
